### ISSUE TITLE
[lain] async widgets issue

### ISSUE THREAD

**Issue by HorizonShadow** [copycat-killer/awesome-copycats#134] opened 2017-01-19 01:38 UTC
Changed `city_id` to 595776, restarted awesome. Weather widget remains on N/A.

I manually ran the api request to openweather to make sure the api key and id and everything and it worked fine.

**Comment by copycat-killer** [comment] 2017-01-19 13:00
You're asking the data for [Pikelionys](https://lt.wikipedia.org/wiki/Pikelionys), a place with a demographic counter of 88 in 2011.

This is not a city, but a county/village with density << 1000, so the `city ID` can't work.

If you really want to be so specific, you can modify `current_call` and `forecast_call` to make them use `q` instead of `id`, and set `city_id` to your settlement name:

```lua
local myweather = lain.widgets.weather({
    current_call = "curl -s 'http://api.openweathermap.org/data/2.5/weather?q=%s&units=%s&lang=%s&APPID=%s'",
    forecast_call = "curl -s 'http://api.openweathermap.org/data/2.5/forecast/daily?q=%s&units=%s&lang=%s&cnt=%s&APPID=%s'",
    city_id = "Pikelionys,LT",
    weather_na_markup = markup("#eca4c4", "N/A "),
    settings = function()
        descr = weather_now["weather"][1]["description"]:lower()
        units = math.floor(weather_now["main"]["temp"])
        widget:set_markup(markup("#eca4c4", descr .. " @ " .. units .. "°C "))
    end
})
```

Otherwise, Pikelionys is just 5 km from Jieznas: meteorologically speaking there's almost no difference, so you could use Jieznas ID instead: 598854. Check it yourself: [Jieznas](http://api.openweathermap.org/data/2.5/weather?id=598854&units=metric&lang=en&APPID=3e321f9414eaedbfab34983bda77a66e); [Pikelionys](http://api.openweathermap.org/data/2.5/weather?q=Pikelionys,LT&units=metric&lang=en&APPID=3e321f9414eaedbfab34983bda77a66e).

**Comment by HorizonShadow** [comment] 2017-01-19 14:19
Sorry, that was a typo. The ID is 5957776 (three sevens). 

I just tried London, which also didn't work, and then tried using the query param instead of ID, which again didn't work.

I still have N/A displayed.

**Comment by copycat-killer** [comment] 2017-01-19 15:21
I am unable to reproduce, here the widget works fine with your ID.

I assume you have awesome >= 4.0, Lua >= 5.3 and curl installed.

Does

```shell
curl -s 'http://api.openweathermap.org/data/2.5/weather?id=5957776&units=metric&lang=en&APPID=3e321f9414eaedbfab34983bda77a66e'
```

return a correct JSON? If not, you can use whatever tool you like, just modify the above mentioned arguments:

```lua
local myweather = lain.widgets.weather({
    current_call = "your_fetcher_here 'http://api.openweathermap.org/data/2.5/weather?q=%s&units=%s&lang=%s&APPID=%s'",
    forecast_call = "your_fetcher_here 'http://api.openweathermap.org/data/2.5/forecast/daily?q=%s&units=%s&lang=%s&cnt=%s&APPID=%s'",
    city_id = 5957776,
    weather_na_markup = markup("#eca4c4", "N/A "),
    settings = function()
        descr = weather_now["weather"][1]["description"]:lower()
        units = math.floor(weather_now["main"]["temp"])
        widget:set_markup(markup("#eca4c4", descr .. " @ " .. units .. "°C "))
    end
})
```

or you may have a problem with `asynchshell`? Please try the MPD widget too and tell me if it's working.

**Comment by HorizonShadow** [comment] 2017-01-19 15:56
```
curl -s 'http://api.openweathermap.org/data/2.5/weather?id=5957776&units=metric&lang=en&APPID=3e321f9414eaedbfab34983bda77a66e'
{"coord":{"lon":-66.67,"lat":45.95},"weather":[{"id":600,"main":"Snow","description":"light snow","icon":"13d"}],"base":"stations","main":{"temp":-6.4,"pressure":1015,"humidity":92,"temp_min":-7,"temp_max":-6},"visibility":9656,"wind":{"speed":1,"deg":90},"clouds":{"all":90},"dt":1484836440,"sys":{"type":1,"id":3417,"message":0.2043,"country":"CA","sunrise":1484827262,"sunset":1484860488},"id":5957776,"name":"Fredericton","cod":200
```
There's nothing at all displayed for the MPC module. No N/A or anything.  MPD and MPC are both installed, MPD is runnning, and playing a song.

**Comment by copycat-killer** [comment] 2017-01-19 17:35
Let's see if this is a duplicate of https://github.com/copycat-killer/lain/issues/145

Try following [this suggestion](https://github.com/copycat-killer/lain/wiki/Widgets#note).

**Comment by HorizonShadow** [comment] 2017-01-19 19:27
I wasn't 100% what you wanted me to do to that line, but I changed it to point to bash, then dash, then back to sh. There was no difference with any of them. 

Bash is my default shell, by the way.

**Comment by copycat-killer** [comment] 2017-01-20 20:01
I started a big update which will make lain completely asynchronous: `asynchshell` has been removed, and `awful.spawn.easy_async` is being used.

Please `git pull` latest lain and check if you still have issues with weather and MPD widgets.

**Comment by HorizonShadow** [comment] 2017-01-22 23:17
I git pulled the latest lain, and awesome crashed.

**Comment by HorizonShadow** [comment] 2017-01-23 01:13
Alright - Reinstalled it from scratch, and the weather is working.

By the way, when I was reinstalling, I had to manually clone lain into the directory and I had to rename awesome-freedesktop to freedesktop to get everything working. 

I was getting a public key error or something when cloning awesome-copycats on the lain submodule, which was preventing it from cloning.

**Comment by copycat-killer** [comment] 2017-01-23 12:40
When you need to reinstall, please follow the [guide](https://github.com/copycat-killer/awesome-copycats#installation).

**Closed by copycat-killer** 2017-01-23 12:40 UTC
Labels: wrong scope

**Comment by HorizonShadow** [comment] 2017-01-23 14:39
Yup, that was with the git installation.
