### ISSUE TITLE
quakeconsole: multiscreen support

### ISSUE THREAD

**Issue by Jesus-21** [copycat-killer/awesome-copycats#132] opened 2017-01-02 14:30 UTC
Hi,
I had a quite old version of awesome copycat that used scratchdrop so far and updated it recently.
I guess the quakeconsole replacement is supposed to do the same job but this is not what I experienced.

First of all, here is the thing I changed that concerns quakeconsole:
```lua
-- quake terminal                                      
local quakeconsole = {}                                
for s = 1, screen.count() do         
    -- force app="xterm" because it is not my terminal by default
    quakeconsole[s] = lain.util.quake({ app = "xterm" })
end                                                    
-- }}}

-- [...]

-- Dropdown terminal                                  
awful.key({ modkey,           }, "z",      function ()
    quakeconsole[mouse.screen]:toggle()      
    -- debug just to check that mouse.screen is valid 
    naughty.notify({
        preset = naughty.config.presets.critical,         
        title = "Oops, there were errors during startup!",
        text = mouse.screen 
    })                  
end),                                                                                        
```

This is very little customization but here is the problems I have:

- I have to press modkey+z multiple times before a terminal is shown
- my ~/.Xresources is not used
- even though mouse.screen point to the good screen, it will toggle a console on the wrong screen if it has been spawned already.
- last but not least, sometimes instead of being 0.25 of my screen height it takes the whole height (FYI I use  awful.layout.suit.max as default layout)

Maybe I did something wrong in my config, if I can provide further explanation let me know :)

That problem bother me a lot because this a feature that I use a lot and it became very erratic since I updated, I hope you'll be able to help me here :'(

**Comment by copycat-killer** [comment] 2017-01-03 10:42
I had to use `text = tostring(mouse.screen)` instead, otherwise there are problems with `naughty` here.

Paste me your `rc.lua`.

**Comment by Jesus-21** [comment] 2017-01-03 11:10
You can find my whole rc.lua [here](https://raw.githubusercontent.com/Jesus-21/awesome-copycats/custom/rc.lua.multicolor)

I added a few extra things from my original post but the result is the same

PS: I don't know if this might change anything bu for what it worth, here is my awesome --version
```
awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔
```

**Comment by copycat-killer** [comment] 2017-01-03 11:32
Try this:

```lua
-- quake terminal
local quakeconsole = {}
for s = 1, screen.count() do
   quakeconsole[s] = lain.util.quake({
       app = "xterm",
       border = 0,
       width = 0.999, -- or reset to 1 if not working good
       horiz = "left"
   })
end
```

and remove that `math.floor` from the key binding:

```lua
    -- Dropdown terminal
    awful.key({ modkey,	          }, "z",      function ()
        quakeconsole[mouse.screen]:toggle()
    end),
```

Tell me how may monitors you have, and their resolutions.

**Comment by copycat-killer** [comment] 2017-01-03 11:34
But first, **update** to latest lain commit.

**Comment by Jesus-21** [comment] 2017-01-03 13:01
Well, those changes did not affect the behavior in any way sadly :(

I have 2 monitors, both 1920x1080, it's even the same model and my xorg.conf is generated by nvidia-settings.

**Comment by copycat-killer** [comment] 2017-01-04 10:20
I am unable to reproduce it, with a 1080p monitor and `max` layout.

Try `quake` with the default `rc.lua` (usually available in `/etc/xdg/awesome`).

If the issue persists, I'll make you use a debugging version.

**Comment by Jesus-21** [comment] 2017-01-04 10:37
Well, no luck either with the default rc.lua
Event weider, the terminal popped up from bottom, not top :/

**Comment by copycat-killer** [comment] 2017-01-04 11:21
If you set the spawn position in the args, it works as expected?

**Comment by copycat-killer** [comment] 2017-01-04 11:32
Try this [version](https://gist.github.com/copycat-killer/c55732c2be6d91fba685db6cf7a1ae24).

```shell
cd ~/.config/awesome/lain/util
mv quake.lua quake.lua.orig
wget https://gist.githubusercontent.com/copycat-killer/c55732c2be6d91fba685db6cf7a1ae24/raw/2e88af8a6917ef5f1da8ca1ac19574bf96164f55/quake.lua
```

**Comment by Jesus-21** [comment] 2017-01-04 11:32
No, no, I have the same exact problems (wrong screen spawing, wrong size, etc.)

**Comment by copycat-killer** [comment] 2017-01-04 11:36
Try this [version](https://gist.github.com/copycat-killer/c55732c2be6d91fba685db6cf7a1ae24).

```shell
cd ~/.config/awesome/lain/util
mv quake.lua quake.lua.orig
wget https://gist.githubusercontent.com/copycat-killer/c55732c2be6d91fba685db6cf7a1ae24/raw/2e88af8a6917ef5f1da8ca1ac19574bf96164f55/quake.lua
# restart awesome and retry
```

**Comment by Jesus-21** [comment] 2017-01-04 13:03
With this version of `quake.lua` I don't have the size issue anymore (`conf.geometry` being fixed) but I noticed that the dropdown overlaps on my second screen (couple pixel, maybe due to the border).

But it only dropdown on screen 1. The "funny" thing is that if I'm focus screen 2 and press multiple times Mod4+z it spawns a new dropdown each times instead of toggling

**Comment by copycat-killer** [comment] 2017-01-04 18:12
Try again with [latest revision](https://gist.github.com/copycat-killer/c55732c2be6d91fba685db6cf7a1ae24).

**Comment by Jesus-21** [comment] 2017-01-05 08:28
Well now this is OK-ish
Now that the border is gone, the QuakeDD client does not overlap on my second screen tag. 
The result is that the toggle works well now even from screen 2. 

The last problem is that it will only drop down on screen 1, even when a tag/client on screen 2 has the focus, it will show on screen 1.

**Comment by copycat-killer** [comment] 2017-01-05 16:59
That's not a problem, just a static definition for the `screen` argument.

I added the feature to follow the `mouse.screen`, removed the sticky setting, unforced 1080p, and using `screen` instead of `capi`.

[Try again](https://gist.github.com/copycat-killer/c55732c2be6d91fba685db6cf7a1ae24).

**Comment by Jesus-21** [comment] 2017-01-06 09:36
It works great on screen 1 even though I think that you should substract the border size when computing size

```lua
if self.width  <= 1 then width = math.floor(geom.width * self.width) - 2 * self.border end
```

But on screen 2 it does not work... It does create QuakeDD xterm instances as I can see multiple processes spawnned with `ps aux | grep xterm` but those are never to be seen, I don't know where they are.

**Comment by Jesus-21** [comment] 2017-01-06 09:39
I found an almost working work around:
```lua
local quakeconsole = {}                                                         
for s = 1, screen.count() do                                                    
   quakeconsole[s] = lain.util.quake({ 
    app = "xterm",  
    horiz = "left", 
    screen = s, 
    name = "QuakeDD" .. s 
})
end                      
```                                                       
`horiz = "left"` is necessary otherwise the dropdown is centered for the whole display (half on each screen)

 `name = "QuakeDD" .. s` is to avoid having xterms with same name. I guess that might cause problems when `quake:display` `calls awful.client.iterate` even though the `screen` arguments is provided (I will look further into that)

Last problem is that from screen 2, first time I press Mod4+z, the dropdown appear on screen 1 with the wrong size, on second press another one appear one screen 2 with proper size and then it behave well.

**Comment by copycat-killer** [comment] 2017-01-06 12:45
> `horiz = "left"` is necessary otherwise the dropdown is centered for the whole display (half on each screen)

Indeed, that's the expected behaviour.

> name = "QuakeDD" .. s is to avoid having xterms with same name. I guess that might cause problems when quake:display calls awful.client.iterate even though the screen arguments is provided (I will look further into that)

This guess doesn't seem sound to me, but I'll wait for your further investigation.

> Last problem is that from screen 2, first time I press Mod4+z, the dropdown appear on screen 1 with the wrong size, on second press another one appear one screen 2 with proper size and then it behave well.

Test [revision 14](https://gist.github.com/copycat-killer/c55732c2be6d91fba685db6cf7a1ae24) with this:

```lua
for s = 1, screen.count() do
    quakeconsole[s] = lain.util.quake({
        followtag = true,
        name      = "QuakeDD" .. tostring(s) -- try also without this
    })
end
```
You don't need to set `xterm`, because it's the default client.

Try also setting sticky to true [here](https://gist.github.com/copycat-killer/c55732c2be6d91fba685db6cf7a1ae24#file-quake-lua-L76).

PS: are you able to update to Awesome 4.0? It'd be better, since lain too is realigning to it (`quake` is already updated).

**Comment by Jesus-21** [comment] 2017-01-06 13:12
\o/
Revision 14 is the charm!
My guess with `"QuakeDD" .. tostring(s)` was not accurate indeed it was just a side effect of screen 2 spawing terminal on screen 1.

`followtag` is the only mandatory argument for a flawless usage then.

I don't have Awesome 4.0 yet because it didn't hit Arch official repositories yet but I can give a shot to the AUR to test that if it can help you :)

**Comment by copycat-killer** [comment] 2017-01-06 15:58
> I don't have Awesome 4.0 yet because it didn't hit Arch official repositories yet but I can give a shot to the AUR to test that if it can help you :)

Yeah, if you can test `lain-git` with `awesome-git` from the AUR and report back, we can definitely close this.

**Comment by Jesus-21** [comment] 2017-01-06 16:28
Yep, I confirm that it works great with Awesome 4.0 and the latest lain

Thank you very much!

**Comment by copycat-killer** [comment] 2017-01-06 17:16
Thanks to you for making me enhance it with multiscreen support.

**Comment by copycat-killer** [comment] 2017-01-12 17:39
@Jesus-21 Because of https://github.com/copycat-killer/lain/issues/263, now `followtag` is true by default.

**Comment by copycat-killer** [comment] 2017-01-12 19:40
@Jesus-21 Sorry, forget the previous post, it is and has to be `false` by default.

**Comment by liquiddandruff** [comment] 2017-09-03 07:11
Seems to be broken again on current release. Similar failure mode, but now pressing mod+z multiple times always gives the error: `Oops, an error happened! /usr/share/awesome/lib/awful/client.lua:1090: invalid object`.

```
$ awesome -v
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

```
$ xrandr --current
Screen 0: minimum 8 x 8, current 3286 x 1080, maximum 32767 x 32767
LVDS1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 293mm x 165mm
   1366x768      60.07 +
   1024x768      60.00
   1024x576      60.00
   960x540       60.00
   800x600       60.32    56.25
   864x486       60.00
   640x480       59.94
   720x405       60.00
   680x384       60.00
   640x360       60.00
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 connected 1920x1080+1366+0 (normal left inverted right x axis y axis) 480mm x 270mm
   1920x1080     60.00*+  50.00    59.94    59.99
   1920x1080i    60.00    50.00    59.94
   1600x1200     60.00
   1680x1050     59.88
   1280x1024     75.02    60.02
   1440x900      59.90
   1280x960      60.00
   1366x768      59.79
   1152x864      75.00
   1280x720      60.00    50.00    59.94
   1024x768      75.03    70.07    60.00
   832x624       74.55
   800x600       72.19    75.00    60.32    56.25
   720x576       50.00
   720x480       60.00    59.94
   640x480       75.00    72.81    66.67    60.00    59.94
   720x400       70.08
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
  1366x768 (0x49) 70.714MHz -HSync -VSync
        h: width  1366 start 1414 end 1446 total 1486 skew    0 clock  47.59KHz
        v: height  768 start  770 end  775 total  792           clock  60.08Hz
```

I am using the powerarrow-darker theme and up-to-date rcs.

**Comment by copycat-killer** [comment] 2017-09-03 10:16
@liquiddandruff Seems that your problem is an invalid `toscan` screen [here](https://github.com/copycat-killer/lain/blob/master/util/quake.lua#L39). To confirm it, set a static `screen` argument, for instance the first one.

Also, is your `quake` configuration different from the default Powearrow Dark one?

**Comment by liquiddandruff** [comment] 2017-09-04 05:25
I messed around a lot yesterday night with `xrandr` and now the quake console does not give me anymore errors. It seems this problem came up due to what appears to be a suboptimal use of `xrandr` on my part. 

What I did before:

```
xrandr --output HDMI1 --mode 1920x1080 --above LVDS1
```

What works now:

```
xrandr --output HDMI1 --primary --mode 1920x1080 --output LVDS1 --auto --below HDMI1
```

It seems putting the HDMI as primary display did the trick. Maybe negative coordinates was an issue?

Of note however, is that the console only ever pops up on the primary monitor, and not on the focused screen. 

I have not modified my `quake` configuration. I can try setting a static `screen` argument with my initial `xrandr` attempt once I am free.

**Comment by copycat-killer** [comment] 2017-09-04 10:15
> Of note however, is that the console only ever pops up on the primary monitor, and not on the focused screen.

Try setting `followtag = true`. Maybe `onlyone = true` too for performance.

**Comment by liquiddandruff** [comment] 2017-09-05 09:32
Setting `followtag = true` works and a quake terminal appears on the screen I have focus on, but it doesn't seem `onlyone = true` does anything; pressing it again for the first time on a new screen spawns a new terminal instead of doing what's expected.

**Closed** 2017-09-05 09:48 UTC
Labels: enhancement, lain

**Comment by liquiddandruff** [comment] 2017-09-05 10:03
Sorry, I noticed the issue was closed but there's just one last thing: setting `onlyone = true` does not seem to pop up the same quake console on each screen. Instead, a new one appears on each screen. If this setting is indeed supposed to raise the same quake console client on each screen, then I don't think it is working for me.

Thanks again for your work.

**Comment by copycat-killer** [comment] 2017-09-05 10:13
The flag is used just to pass a `nil` argument to [`awful.client.iterate`](https://awesomewm.org/doc/api/classes/client.html#awful.client.iterate), meaning to use all screens when iterating through clients in order to get the eventually existing instance. It's dead simple.

Let's continue here: https://github.com/copycat-killer/lain/pull/339
