### ISSUE TITLE
multi-monitor window effects overhang

### ISSUE THREAD

**Issue by bluTaz** [copycat-killer/awesome-copycats#160] opened 2017-02-22 01:57 UTC
Using two screens, window effects bleed onto the next monitor. Attached are two screenshots. I can eliminate the shadow simply by disabling compton but lose transparency effects.. non-issue. Using a quake terminal however, the window borders seem to bleed over terribly, my assumption is that window geometry doesn't take into account the border size when positioned.

![screen](https://cloud.githubusercontent.com/assets/1010685/23193722/5cfef974-f878-11e6-9c8b-62b99533b8a6.png)
![screen2](https://cloud.githubusercontent.com/assets/1010685/23193724/6177f74e-f878-11e6-8df4-2dc3971fe486.png)

**Comment by bluTaz** [comment] 2017-02-22 02:39
actually I believe this is related to [issue 159](https://github.com/copycat-killer/awesome-copycats/issues/159)

**Comment by copycat-killer** [comment] 2017-02-22 11:25
#159 might be different, as we're talking about `wibox` there.

> my assumption is that window geometry doesn't take into account the border size when positioned

But `quake` does it for [width](https://github.com/copycat-killer/lain/blob/master/util/quake.lua#L107), so where the cause can be?

Trivial question, does it happen with default `rc.lua` too?

Try run your configuration with `Xephyr` as suggested [here](https://github.com/copycat-killer/awesome-copycats/issues/159#issuecomment-280880311), and see if is there any `stderr` when spawning `quake`.

Also, paste me your `quake` settings, and your `{rc,theme}.lua` if you have set anything particular.

**Comment by bluTaz** [comment] 2017-02-23 00:39
It only occurs with window borders, thinner borders give less overhang and If I go into the theme.lua and set borderwidth to 0, there is no overhang. I had the same issue as in #159 using vertex. The issue seemed to be with the screen layout. I'm using two different screen resolutions so that seems to be be the issue with the wibox as adjusting where I position the monitor in Arandr moved the wibox around, as the entire screen layout adapts the height of the larger monitor ( dark gray area in screenshot).
![screen3](https://cloud.githubusercontent.com/assets/1010685/23239513/b6f40182-f935-11e6-91d8-e99d1b6732a4.png)

![screen4](https://cloud.githubusercontent.com/assets/1010685/23239651/7e2c3e5e-f936-11e6-9053-cfc820576513.png)

**Comment by bluTaz** [comment] 2017-02-23 00:43
Also adding a gap in the layout between screens with arandr, eliminates the shadow bleed, but theres still the slight cutoff on the edge of a quake terminal aligned to an edge.

**Comment by copycat-killer** [comment] 2017-02-23 13:40
While I investigate further, you confirm that it doesn't happen with default config, right?

**Comment by bluTaz** [comment] 2017-02-24 00:58
if you're refering to the one provided in this repo, rc.lua.template, no there is none, at least not noticebly visible, changing border_width from 1 to 2 in theme.lua does overhang however.

**Comment by copycat-killer** [comment] 2017-02-24 12:27
I was referring to `/etc/xdg/awesome/rc.lua`, or `/usr/local/etc/xdg/awesome/rc.lua` if you're using git branch.

Check if the border issue happens with it too.

**Comment by bluTaz** [comment] 2017-02-24 15:29
the default config doesn't include the quake utility, Note that this only happens with a quake terminal. Maximized windows do not bleed over nor windows tiled to the edges, only a quake terminal. I just noticed you keep a seperate repo for lain, should this be moved there?

**Comment by copycat-killer** [comment] 2017-02-24 17:41
> Note that this only happens with a quake terminal. 

I also meant to use `quake` with it for the check. Sorry, I thought it was obvious.

**Comment by bluTaz** [comment] 2017-02-24 22:32
Ok, so I got quake working but it doesnt seem to use border_width at all, changing it in the default theme didn't affect it so with the default value of 1, overhang was either too small to matter or non-existant. I actually don't use borders but I thought I'd pass the observation on. I'd dig into it myself but my programming skills are noob lol.

**Comment by copycat-killer** [comment] 2017-02-25 10:21
> I'd dig into it myself but my programming skills are newb lol.

If you could do as I [asked](https://github.com/copycat-killer/awesome-copycats/issues/160#issuecomment-281642965), maybe I'd find a solution.

> Also I'm not sure where to set quake to follow the border_width provided in the default theme.

In `quake` input arguments. Uncomment the one you like:

```lua
awful.screen.connect_for_each_screen(function(s)
    -- Quake application
    s.quake = lain.util.quake({
        -- border = theme.border_width, -- if you're using awesome-copycats structure
        -- border = beautiful.border_width, -- if you are not
        border = 2, -- otherwise
        -- [...]
    })
    -- [...]
```

**Comment by WillianPaiva** [comment] 2017-03-03 12:27
i have being trying to track this problem a bit and i have the same when i use for exemple MPV on fullscreen and maximized windows what did work around was adding this for maximized : 
```
client.connect_signal("property::maximized", function(c) 
    c.border_width = c.maximized and 0 or beautiful.border_width
end)

```
but the same for fullscreen don't work it still movin the window and overlaping the next screen

**Comment by copycat-killer** [comment] 2017-03-03 13:16
> but the same for fullscreen don't work it still movin the window and overlaping the next screen

You can try using a signal like this:

```lua
client.connect_signal("property::maximized", function(c) 
    c.border_width = c.maximized and 0 or beautiful.border_width
    if c.first_tag.name:match("fullscreen") then -- fullscreen (max) layout
        -- do stuff here 
    end
end)
```

Read the [API](https://awesomewm.org/doc/api/classes/client.html) in order to *do stuff*.

**Comment by copycat-killer** [comment] 2017-03-12 11:02
@bluTaz @WillianPaiva Your issue is related to https://github.com/awesomeWM/awesome/issues/1607

Closing this and #159.

**Closed by copycat-killer** 2017-03-12 11:02 UTC
